### ISSUE TITLE
Server crashes on url `/bitcoin/` 

### ISSUE THREAD

**Issue by notmandatory** [lvaccaro/btctipserver#19]
Seems to be a known issue in server.rs line 67, a TODO to handle missing address. Probably other places we need to change unwraps into ? and do some additional error handling.

**Comment by lvaccaro** [comment]
Related to "/bitcoin/" branch, another good feature could be check if the input address is owned by the node.

**Comment by RCasatta** [comment]
#21

**Comment by lvaccaro** [comment]
looks fixed, thanks
