### ISSUE TITLE
Error with "Open in wallet" link

### ISSUE THREAD

**Issue by notmandatory** [lvaccaro/btctipserver#25]
Unable to open Bitcoin Core Qt app with "Open in wallet" link. Got error:
```
'bitcoin://' is not a valid URI. Use 'bitcoin:' instead.
```

Test URL: https://btctip.lvaccaro.com/bitcoin/?bc1q9774wr2jjc0j797peue0wgsp0khvxtpd2l96xu

Browser: Firefox 87.0
OS: OSX 11.2.3 (Big Sur)
Bitcoin Core: 0.20.0

**Comment by lvaccaro** [comment]
thanks to report it

**Comment by lvaccaro** [comment]
Solved in https://github.com/lvaccaro/btctipserver/pull/26 by @josediegorobles . Thanks for the PR
