### ISSUE TITLE
New unused addresses

### ISSUE THREAD

**Issue by notmandatory** [lvaccaro/btctipserver#7]
What do you think about adding an endpoint that returns the first unused address? I think the `/bitcoin/api/new` URL could be abused to increment up the XPUB index to a number outside the normal wallets gap limit. But a new URL (ie. `/bitcoin/api/unused`) could return a new address only if the current index has already received a UTXO. There is the chance that due to bad timing an address could be spent to more than once before the wallet registered that the address was used, but for most people getting tips I doubt this will happen very often. If you think this makes sense I'm happy to work on a PR for it.

**Comment by lvaccaro** [comment]
This sound as good first issue :-)

**Comment by notmandatory** [comment]
Figo! I've started investigating and this might be easiest to add in `bdk` as a new function on `Wallet`, since that's where we know the current xpub index. Will post a link here if I create any related `bdk` PR.

**Comment by notmandatory** [comment]
BTW this is also a privacy issue since if we allow requesting new addresses a malicious person could keep making requests until they know every address for your wallet.
