### ISSUE TITLE
No need for change_descriptor

### ISSUE THREAD

**Issue by notmandatory** [lvaccaro/btctipserver#8]
As I understand it this server's job will be primarily to provide a URL to generate new receive addresses from a XPUB descriptor for a receiving tips. So I don't think you need to configure a `change_descriptor`, the BDK wallet doesn't require it. I assume anyone using this server will have a spending wallet setup somewhere else with the same descriptor but with the XPRV key.

**Comment by lvaccaro** [comment]
Yes, I full agree with you. Thanks to report it!

**Comment by notmandatory** [comment]
resolved by #9
